### ISSUE TITLE
Azure Blob-Level Tiering

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-storage-php#113]
Hi there,

we are very interested in the Azure "Archive" Tiering, which makes use of the new Blob-Level Tiering Functionality. As far as I can see, this SDK does not support this Feature at the Moment, is this correct?
Any Plans to add this Functionality?

Thanks,
Christoph

**Comment by katmsft** [comment]
Hi Christoph,
PHP library is now preparing for GA release, which targets to service version 2016-05-31. Unfortunately this version does not support Azure Archive Tiering. The version that supports this feature will presumably be the first version after GA release, but it is still in the planning phase. Please stay tuned and we will give you the timeline once it's available.
In the meantime, there are some SDKs that already supports archive like [azure-storage-node](https://github.com/Azure/azure-storage-node/commit/d789db2de5185b28486638d2513e4ef2b07ecf1f), please take a look if interested.
Best regards,
Azure Storage Client Library Team.

**Comment by boredom2** [comment]
Hi there - are there any Updates on the Availibility of this Feature in the Storage SDK?

**Comment by katmsft** [comment]
Hi, thanks for regularly checking this.

Our current plan is to support this feature soon. However due to the probable test framework change that needs to be done to support testing this feature, we cannot provide a solid release date. We are aiming to release it around Aug. 2018.

In the meantime, we welcome our community to contribute to whatever feature is urgently needed for them. We will be available to review the design and code change, and will provide any assist needed.

**Comment by boredom2** [comment]
Thanks for the Update!

**Comment by XiaoningLiu** [comment]
@boredom2 Blob tier has been supported in azure-storage-blob@1.2.0.

**Comment by boredom2** [comment]
Hi there, yes, I know , thank you so much. 👍 
Already updated and itnegrated, works perfectly.
