### ISSUE TITLE
Fatal error in BlobSamples

### ISSUE THREAD

**Issue by franciscocervantes** [Azure/azure-storage-php#155]

**Comment by franciscocervantes** [comment]
I just trying to make some test runing one of the Samples and Im getting this error:

[Tue Oct 23 12:23:25.444779 2018] [php7:error] [pid 4414] [client 79.146.86.176:57467] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to MicrosoftAzure\\Storage\\Common\\Models\\Metrics::create() must be of the type array, null given, called in /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Models/ServiceProperties.php on line 70 and defined in /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Models/Metrics.php:54\nStack trace:\n#0 /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Models/ServiceProperties.php(70): MicrosoftAzure\\Storage\\Common\\Models\\Metrics::create(NULL)\n#1 /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Models/GetServicePropertiesResult.php(52): MicrosoftAzure\\Storage\\Common\\Models\\ServiceProperties::create(Array)\n#2 /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Internal/ServiceRestTrait.php(110): MicrosoftAzure\\Storage\\Common\\Models\\GetServicePropertiesResult::create(Array)\n#3 /home/Legalbono/fintonic/vendor/guzzlehttp/promises/src/Promise.php(203): MicrosoftAzu in /home/Legalbono/fintonic/vendor/microsoft/azure-storage-common/src/Common/Models/Metrics.php on line 54

I just defined the connectionString, do I have to do anything else???

**Comment by katmsft** [comment]
Since there hasn't been any feedback from the customer, this issue will now be closed.

**Comment by mkgn** [comment]
Reopening because I am getting the same error. According to you ""HourMetrics" will return by storage server by default." Meaning is there any other configuration I should do when creating storage in Azure? I have just enabled public access and everything is as default.

Also I see that the code doesn't seem to work well because for me to get to this point I had to change many places. Is there a newer version of the code that works?
