### ISSUE TITLE
Append blob support

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-storage-php#26]
seems missing append blob type support within this SDK

**Comment by Fuitad** [comment]
+1

**Comment by EdouardNaze** [comment]
I made some tests in my side, and i successed to have Append Blob more or less functional. 
I reuse a lot of Page Blob code, and adapt it for Append Blob.
I just have to test, refactor and document and learn how make a pull request :)

**Comment by katmsft** [comment]
Thanks for the effort @EdouardNaze. We do have AppendBlob support in our backlog as well as many other service feature parity; unfortunately it’s not the immediate next item we planned. your contribution will be very much welcome.

Since supporting Append Blob include creating new interfaces and adding new logic to some of the old interfaces, to facilitate your work, we’d like to share some important thing: First is to remind you about the CONTRIBUTING.md we have in the project, especially the ‘Testing Features’ part. Also please review the provided guidelines for making a pull request, I am sure this will clear out some obstacles for you. Lastly, we’d like to sync up your design for both the implementation and test code before you make the pull request, or better before you even implement the code. Hopefully this will save you some extra work of going back and forth on the review of the pull request due to the problems that can be eliminated during this phase.

**Comment by katmsft** [comment]
@EdouardNaze @Fuitad @allenhula 
Append blob is now supported in release 0.14.0. Check it out!
