### ISSUE TITLE
Use static instead of parent to support easier extensibility

### ISSUE THREAD

**Issue by dluces** [Azure/azure-storage-php#28]
While wanting to work around #27, in my setup, it made sense to just extend `MicrosoftAzure\Storage\Common\ServicesBuilder` to override the `blobAuthenticationScheme` method to return an instance of an extended version of the `SharedKeyAuthScheme` class, where the workaround is applied. However, in `ServicesBuilder`, the `getInstance` method is creating an instance of its own class, when it could do `static::$_instance = new static();`, for example. This made me have to override the `getInstance` method accordingly. Also, the `$_instance` variable is private, so I had to use a different variable.
When extending `MicrosoftAzure\Storage\Common\Internal\Authentication\SharedKeyAuthScheme`, I would have expected to just need to override the `computeCanonicalizedResource` method. However, it was being called from the `computeSignature` where it actually called it like this: `$canonicalizedResource = parent::computeCanonicalizedResource(...);`. Using the `parent` keyword instead of the `static` keyword, made me have to override the `computeSignature` method as well.
Minor fixed in these classes would have made applying a workaround to the issue much faster and cleaner. It would be awesome to set this as the default practice to allow for better extensibility of the SDK.
As per the guidelines for contributing, I would need to have this discussed before creating a PR.

**Comment by katmsft** [comment]
Late static binding is a fine feature of the language itself, however I am a little bit concern of the usage here.
The scenario of users extending these two classes here is when they want to modify something that does not work properly, which is the cases that we strive to avoid. Also it is hard for me to imagine why we would, or a user would, want to extend these classes rather than use them as is, when they function correctly.
However, it makes sense to use `static` over `parent` in the classes that we imagine user would extend, yet I have not gone through the entire project and can be confidently say that there is or isn't any. I will bare this in mind when developing in the future.
Also this SDK is currently in MIT license so that if you need to work-around some bugs, feel free to change the code locally or make pull request if the change is thought to be valuable for the project. This to me helps the project to improve and is welcome on all accounts.
Lastly, thanks for the advice and contribution. Feel free to comment or correct me if I'm wrong.

**Comment by dluces** [comment]
Hey @katmsft. I think you have a valid point. When things work correctly, we will hardly ever have the need to customize the classes in my example. However:

1. Things are not always perfect and being able to *quickly* work around issues means a great deal
2. Having the ability to customize them does not hurt even when they work perfectly

In my experience, specially with #27, it would have been valuable to me having an easier way to work around the issue while also contributing to the SDK (as in #34). I still think you guys have made a good job at making the SDK extensible though and I really appreciate that. Actually, this suggestion might take more effort than the benefits it will provide. It would have taken less effort while retaining the benefits if this would have been considered when first starting the project, but I understand that it might not be worth going through the whole thing just for this.

Anyway, thanks for the consideration. Cheers!

**Comment by katmsft** [comment]
Suggest to close.
