### ISSUE TITLE
Linux memory usage increment

### ISSUE THREAD

**Issue by thiennx** [Azure/azure-storage-php#31]
I set up listBlobs sample run every 5 minutes by cron job.
Memory usage percentage increase from 15% to 30% after 1 days and to 40% after 2 days but is not auto released. 
I dont know reason, is this SDK issues or another reason. Can you check my problem? Thank you

**Comment by katmsft** [comment]
Hi, I need some extra information from you to better investigate on the issue. It would be really helpful if you could provide it.
You said that you run the BlobSample every 5 minutes but only with listBlobs, I assume that you commented other three function calls in the sample. Please confirm.
Also it would be best if you could provide the version and distribution of your Linux system, and possibly the more detailed setup for your cron job. Normally according to your description Cron will start a new process every 5 minutes. It would be very strange and possibly not an SDK related issue if the processes ended successfully.
Thanks for the effort!

**Comment by thiennx** [comment]
Thanks for check my issue.

Yes, I comment out other three function calls in the sample, run listBlobs function only.
My system is Centos 6.5. 
When memory usage percentage was 60% I checked memory information. Dentry cache is increased that is reason. But I don't know why dentry cache is increased quickly when run  listBlobs function.

**Comment by katmsft** [comment]
After some digging I found that the issue was actually related to Guzzle, the HTTP handler for this SDK. There is an article [here](https://www.splyt.com/blog/2014-05-16-optimizing-aws-nss-softoken) where you can find a more detailed description of the root cause. I have tried validating the solution and gladly it worked with my setup, which is a CentOS 6.5 that can reproduce this bug using cron.
```
#Solution:
#Step 1: Install a 3.16.0 or higher version of nss-softokn
sudo yum update -y nss-softokn
#Step 2: Setting the environment variable whenever you run the sample.
export NSS_SDB_USE_CACHE=YES
```
Also, some test is made in Ubuntu but it seems that Ubuntu does not have this issue. Other Linux distribution remain untested for this specific issue.
