### ISSUE TITLE
Add async methods

### ISSUE THREAD

**Issue by tblyler** [Azure/azure-storage-php#35]
It would be nice if there were async methods for calls, or a toggle to specify whether or not the method will use async and return a promise.

**Comment by katmsft** [comment]
It is definitely something that is going to be added once the goal of the development of this SDK has moved from 'feature support' to 'provide convenience'. It is hard to postpone the deliver of File support or Append Blob support only because we want to support async methods. But again, thanks for the advice. It is added to our road-map.

**Comment by katmsft** [comment]
Suggest to close, as it is now supported in 0.12.0

**Comment by vinjiang** [comment]
@tblyler ，feel free to have a try on [0.12.0](https://github.com/Azure/azure-storage-php/releases/tag/v0.12.0) and let us know if you have further questions.
