### ISSUE TITLE
Add support for generation of SAS tokens/signed URLs

### ISSUE THREAD

**Issue by dluces** [Azure/azure-storage-php#66]
We have some code to generate service SAS that we're willing to contribute back to this repo. What would be the best place to put a method to generate service SAS tokens?

Also, @jcorioland published [a gist](https://gist.github.com/jcorioland/731d7ab2aac9b505120a1a80a0188692) with code to generate Account SAS tokens that would be helpful to have as part of the SDK too.

**Comment by katmsft** [comment]
Hi, thanks for the intention for contributing. I have been co-working with @jcorioland for the Account SAS generation lately and I am excited to see you can help implement service level SAS.
As far as I am concerned, we need different methods for different service regarding service level SAS because they have different parameters. Putting them in `SharedAccessSignatureHelper` that @jcorioland implemented is a good choice since the user need not build a service proxy for the SAS generation, and all the SAS generation method can be found in one class. But the name maybe needs a to be changed.

**Comment by dluces** [comment]
Hi @jcorioland 
Thanks! I'll be working based on your work.
And yes, I think I'll be able to send a PR this weekend.

**Comment by jcorioland** [comment]
Hi @dluces @katmsft , FYI I have just pushed a PR #67

**Comment by katmsft** [comment]
Thanks for the great work, the PR has been already merged to dev branch.

@dluces, any updates?

**Comment by dluces** [comment]
@katmsft Thanks! I'll pull dev so I can put my code in the new `SharedAccessSignatureHelper` class and send a PR.

**Comment by dluces** [comment]
@katmsft Sorry for the delay, I've been having other issues. Hopefully I can send this PR soon.

**Comment by dluces** [comment]
@katmsft I've created PR #73, but please beware of the tests (they are invalid right now)

**Comment by katmsft** [comment]
Service SAS is implemented in 0.16.0, @dluces @jcorioland check it out!
