### ISSUE TITLE
Use \DateTime for SharedAccessSignatureHelper $signedExpiry and $signedStart instead of string

### ISSUE THREAD

**Issue by dkarlovi** [Azure/azure-storage-php#97]
While creating a SAS token, you should enforce expiry start and end date times to actually be `\DateTime` instead of string looking like one. Reason is, you're then able to properly format them before pushing into `generateServiceSharedAccessSignatureToken`.

I bring this up as I've been using `$dateTime->format('c')` which passes the current validation, but SAS token will fail as used. Problem is, it's generates `YYYY-MM-DDTHH:MM:SS+00:00` instead of `YYYY-MM-DDTHH:MM:SSZ` which was quite hard to track down.

**Comment by XiaoningLiu** [comment]
@dkarlovi That's a valid request, will add into our backlog.

**Comment by dkarlovi** [comment]
Might consider introducing a new class, `SharedAccessSignatureRequest` (or similar) which could simplify the code here. Functionally the same as a TLS CSR sent to a CA when requesting a new HTTPS key.

It would also allow to have a much simpler proxy method signature should you choose to implement #96.

**Comment by XiaoningLiu** [comment]
@dkarlovi Thanks again! Next release will include the changes to **Use \DateTime for SharedAccessSignatureHelper $signedExpiry and $signedStart instead of string**. This issue will be closed after the release.

For the design improvement, let's continue the discussion on #96. What's the functionality pattern about `SharedAccessSignatureRequest ` and **TLS CSR sent to a CA when requesting a new HTTPS key** you're referring to?

**Comment by dkarlovi** [comment]
@XiaoningLiu great to hear, thanks. Switching the discussing on the signing request over to #96.

**Comment by vinjiang** [comment]
0.18.0 is released
